name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
          cache: 'yarn'
      - name: 安装构建工具
        run: |
          npm install -g node-gyp
          sudo apt-get update
          sudo apt-get install -y python3 make g++
      - name: 安装依赖
        run: yarn install
      - name: 构建
        run: yarn build
      - name: 部署到 Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: win
          directory: dist
